# Generated by Django 5.2.15 on 2026-06-23 13:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0015_puntos_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlicuotaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('codigo_arca', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'alícuota de IVA',
                'verbose_name_plural': 'alícuotas de IVA',
                'db_table': 'items_alicuotaiva',
                'ordering': ['porcentaje', 'nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('simbolo', models.CharField(blank=True, max_length=20)),
                ('codigo_arca', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'db_table': 'items_unidadmedida',
                'ordering': ['nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'categoría de ítem',
                'verbose_name_plural': 'categorías de ítems',
                'db_table': 'items_categoriaitem',
                'ordering': ['empresa__razon_social', '-activo', 'nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'items_marca',
                'ordering': ['empresa__razon_social', '-activo', 'nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], max_length=20)),
                ('se_compra', models.BooleanField(default=False)),
                ('se_vende', models.BooleanField(default=False)),
                ('controla_stock', models.BooleanField(default=False)),
                ('tratamiento_iva', models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('NO_GRAVADO', 'No gravado')], default='GRAVADO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alicuota_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.alicuotaiva')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.categoriaitem')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='nucleo.empresa')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.marca')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.unidadmedida')),
            ],
            options={
                'verbose_name': 'ítem',
                'verbose_name_plural': 'ítems',
                'db_table': 'items_item',
                'ordering': ['empresa__razon_social', '-activo', 'nombre', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriaitem',
            index=models.Index(fields=['empresa', 'activo', 'nombre'], name='idx_categoria_item_emp_act'),
        ),
        migrations.AddConstraint(
            model_name='categoriaitem',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_categoria_item_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['empresa', 'activo', 'nombre'], name='idx_marca_emp_act_nombre'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_marca_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['empresa', 'activo', 'nombre'], name='idx_item_emp_act_nombre'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['empresa', 'tipo', 'activo'], name='idx_item_emp_tipo_activo'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_item_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('se_compra', True), ('se_vende', True), _connector='OR'), name='chk_item_capacidad_operativa'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'PRODUCTO'), ('controla_stock', False), _connector='OR'), name='chk_item_servicio_sin_stock'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alicuota_iva__isnull', False), ('tratamiento_iva', 'GRAVADO')), models.Q(models.Q(('tratamiento_iva', 'GRAVADO'), _negated=True), ('alicuota_iva__isnull', True)), _connector='OR'), name='chk_item_tratamiento_iva'),
        ),
    ]
