# Generated by Django 5.2.15 on 2026-06-29 18:23

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_catalogos_iniciales'),
        ('nucleo', '0015_puntos_venta'),
        ('terceros', '0003_grupos_terceros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_items_proveedores', to='nucleo.empresa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_proveedores', to='items.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_items_proveedor', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'proveedor de ítem',
                'verbose_name_plural': 'proveedores de ítems',
                'db_table': 'items_itemproveedor',
                'ordering': ['empresa__razon_social', 'item__nombre', '-activo', 'proveedor__denominacion'],
                'indexes': [models.Index(fields=['empresa', 'item', 'activo'], name='idx_itemprov_emp_item_act'), models.Index(fields=['empresa', 'proveedor', 'activo'], name='idx_itemprov_emp_prov_act')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'item', 'proveedor'), name='uniq_itemprov_emp_item_prov'), models.UniqueConstraint(models.F('empresa'), models.F('proveedor'), django.db.models.functions.text.Lower('codigo_proveedor'), condition=models.Q(('codigo_proveedor', ''), _negated=True), name='uniq_itemprov_emp_prov_cod_ci'), models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_itemprov_fechas'), models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_itemprov_activo_sin_baja')],
            },
        ),
    ]
