# Generated by Django 5.2.15 on 2026-06-20 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0008_roles_permisos_funcionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El codigo debe respetar la mascara 9.9.99.99.999.', regex='^[0-9]\\.[0-9]\\.[0-9]{2}\\.[0-9]{2}\\.[0-9]{3}$')])),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_contable', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO_NETO', 'Patrimonio Neto'), ('RESULTADO_POSITIVO', 'Ingresos'), ('RESULTADO_NEGATIVO', 'Gastos y perdidas'), ('ORDEN', 'Cuentas de orden')], max_length=20)),
                ('naturaleza', models.CharField(blank=True, choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=10, null=True)),
                ('habilitada', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='nucleo.empresa')),
                ('parent', models.ForeignKey(blank=True, db_column='cuenta_padre_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_hijas', to='contabilidad.cuentacontable', verbose_name='Cuenta superior')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['empresa_id', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_cuenta_empresa_codigo'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('empresa', 'tipo_contable'), name='uniq_cuenta_raiz_empresa_tipo'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^(?:[1-9]\\.0\\.00\\.00\\.000|[1-9]\\.[1-9]\\.00\\.00\\.000|[1-9]\\.[1-9]\\.(?:0[1-9]|[1-9][0-9])\\.00\\.000|[1-9]\\.[1-9]\\.(?:0[1-9]|[1-9][0-9])\\.(?:0[1-9]|[1-9][0-9])\\.000|[1-9]\\.[1-9]\\.(?:0[1-9]|[1-9][0-9])\\.(?:0[1-9]|[1-9][0-9])\\.(?:00[1-9]|0[1-9][0-9]|[1-9][0-9]{2}))$')), name='chk_cuenta_codigo_estructura'), models.CheckConstraint(condition=models.Q(models.Q(('codigo__endswith', '.000'), ('naturaleza__isnull', True)), models.Q(models.Q(('codigo__endswith', '.000'), _negated=True), ('naturaleza__isnull', False), ('naturaleza__in', ['DEUDORA', 'ACREEDORA'])), _connector='OR'), name='chk_cuenta_naturaleza_imputabilidad')],
            },
        ),
    ]
