from django.urls import path

from . import views


app_name = "nucleo"

urlpatterns = [
    path(
        "configuracion/",
        views.configuracion_empresa,
        name="configuracion_empresa",
    ),
    path(
        "configuracion/datos-contribuyente/",
        views.datos_contribuyente,
        name="datos_contribuyente",
    ),
    path(
        "configuracion/sucursales/",
        views.sucursales,
        name="sucursales",
    ),
    path(
        "configuracion/sucursales/nueva/",
        views.sucursal_crear,
        name="sucursal_crear",
    ),
    path(
        "configuracion/sucursales/<int:sucursal_id>/editar/",
        views.sucursal_editar,
        name="sucursal_editar",
    ),

    path(
        "configuracion/puntos-venta/",
        views.puntos_venta,
        name="puntos_venta",
    ),
    path(
        "configuracion/puntos-venta/nuevo/",
        views.punto_venta_crear,
        name="punto_venta_crear",
    ),
    path(
        "configuracion/puntos-venta/<int:punto_venta_id>/editar/",
        views.punto_venta_editar,
        name="punto_venta_editar",
    ),
    path(
        "configuracion/puntos-venta/<int:punto_venta_id>/inactivar/",
        views.punto_venta_inactivar,
        name="punto_venta_inactivar",
    ),
    path(
        "configuracion/actividades/",
        views.actividades_empresa,
        name="actividades_empresa",
    ),
    path(
        "configuracion/actividades/nueva/",
        views.actividad_empresa_crear,
        name="actividad_empresa_crear",
    ),
    path(
        (
            "configuracion/actividades/"
            "<int:empresa_actividad_id>/editar/"
        ),
        views.actividad_empresa_editar,
        name="actividad_empresa_editar",
    ),
    path(
        (
            "configuracion/actividades/"
            "<int:empresa_actividad_id>/inactivar/"
        ),
        views.actividad_empresa_inactivar,
        name="actividad_empresa_inactivar",
    ),
    path(
        "configuracion/actividades/catalogo/buscar/",
        views.catalogo_actividades_buscar,
        name="catalogo_actividades_buscar",
    ),

path(
    "configuracion/ingresos-brutos/",
    views.ingresos_brutos,
    name="ingresos_brutos",
),
path(
    "configuracion/ingresos-brutos/nueva/",
    views.configuracion_iibb_crear,
    name="configuracion_iibb_crear",
),
path(
    "configuracion/ingresos-brutos/<int:configuracion_id>/editar/",
    views.configuracion_iibb_editar,
    name="configuracion_iibb_editar",
),
path(
    "configuracion/ingresos-brutos/<int:configuracion_id>/inactivar/",
    views.configuracion_iibb_inactivar,
    name="configuracion_iibb_inactivar",
),
path(
    (
        "configuracion/ingresos-brutos/<int:configuracion_id>/"
        "jurisdicciones/nueva/"
    ),
    views.jurisdiccion_iibb_crear,
    name="jurisdiccion_iibb_crear",
),
path(
    (
        "configuracion/ingresos-brutos/jurisdicciones/"
        "<int:relacion_id>/editar/"
    ),
    views.jurisdiccion_iibb_editar,
    name="jurisdiccion_iibb_editar",
),
path(
    (
        "configuracion/ingresos-brutos/jurisdicciones/"
        "<int:relacion_id>/inactivar/"
    ),
    views.jurisdiccion_iibb_inactivar,
    name="jurisdiccion_iibb_inactivar",
),
    path(
        "configuracion/parametros/",
        views.parametros_operativos,
        name="parametros_operativos",
    ),
    path(
        "configuracion/parametros/inicializar/",
        views.inicializar_configuracion_empresa,
        name="inicializar_configuracion_empresa",
    ),
]
