TIPOS_COMPROBANTE_VENTA_INICIALES = (
    {
        "codigo_arca": 1,
        "nombre": "Factura A",
        "abreviatura": "FA",
        "clase": "A",
        "especie": "FACTURA",
        "signo": 1,
        "mueve_iva": True,
    },
    {
        "codigo_arca": 2,
        "nombre": "Nota de debito A",
        "abreviatura": "NDA",
        "clase": "A",
        "especie": "NOTA_DEBITO",
        "signo": 1,
        "mueve_iva": True,
        "requiere_comprobante_asociado": True,
    },
    {
        "codigo_arca": 3,
        "nombre": "Nota de credito A",
        "abreviatura": "NCA",
        "clase": "A",
        "especie": "NOTA_CREDITO",
        "signo": -1,
        "mueve_iva": True,
        "requiere_comprobante_asociado": True,
    },
    {
        "codigo_arca": 6,
        "nombre": "Factura B",
        "abreviatura": "FB",
        "clase": "B",
        "especie": "FACTURA",
        "signo": 1,
        "mueve_iva": True,
    },
    {
        "codigo_arca": 7,
        "nombre": "Nota de debito B",
        "abreviatura": "NDB",
        "clase": "B",
        "especie": "NOTA_DEBITO",
        "signo": 1,
        "mueve_iva": True,
        "requiere_comprobante_asociado": True,
    },
    {
        "codigo_arca": 8,
        "nombre": "Nota de credito B",
        "abreviatura": "NCB",
        "clase": "B",
        "especie": "NOTA_CREDITO",
        "signo": -1,
        "mueve_iva": True,
        "requiere_comprobante_asociado": True,
    },
    {
        "codigo_arca": 11,
        "nombre": "Factura C",
        "abreviatura": "FC",
        "clase": "C",
        "especie": "FACTURA",
        "signo": 1,
        "mueve_iva": False,
    },
    {
        "codigo_arca": 12,
        "nombre": "Nota de debito C",
        "abreviatura": "NDC",
        "clase": "C",
        "especie": "NOTA_DEBITO",
        "signo": 1,
        "mueve_iva": False,
        "requiere_comprobante_asociado": True,
    },
    {
        "codigo_arca": 13,
        "nombre": "Nota de credito C",
        "abreviatura": "NCC",
        "clase": "C",
        "especie": "NOTA_CREDITO",
        "signo": -1,
        "mueve_iva": False,
        "requiere_comprobante_asociado": True,
    },
)
