# Generated by Django 5.2.15 on 2026-06-21 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0015_puntos_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números y guion bajo.', regex='^[A-Z0-9_]+$')])),
                ('nombre', models.CharField(max_length=160)),
                ('codigo_arca', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'condición frente al IVA',
                'verbose_name_plural': 'condiciones frente al IVA',
                'db_table': 'terceros_condicioniva',
                'ordering': ['codigo_arca', 'nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números y guion bajo.', regex='^[A-Z0-9_]+$')])),
                ('nombre', models.CharField(max_length=120)),
                ('codigo_arca', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('requiere_numero', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'db_table': 'terceros_tipodocumento',
                'ordering': ['codigo_arca', 'nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')])),
                ('tipo_persona', models.CharField(choices=[('PERSONA_HUMANA', 'Persona humana'), ('PERSONA_JURIDICA', 'Persona jurídica'), ('OTRA', 'Otra')], max_length=30)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('denominacion', models.CharField(max_length=200)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=180)),
                ('sitio_web', models.URLField(blank=True, max_length=300)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condicion_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceros', to='terceros.condicioniva')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceros', to='nucleo.empresa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceros', to='terceros.tipodocumento')),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'db_table': 'terceros_tercero',
                'ordering': ['empresa__razon_social', '-activo', 'denominacion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='DomicilioTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FISCAL', 'Fiscal'), ('COMERCIAL', 'Comercial'), ('ENTREGA', 'Entrega'), ('COBRANZA', 'Cobranza'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('calle', models.CharField(max_length=160)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(blank=True, max_length=80)),
                ('torre', models.CharField(blank=True, max_length=50)),
                ('piso', models.CharField(blank=True, max_length=30)),
                ('departamento', models.CharField(blank=True, max_length=30)),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('localidad', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('partido_departamento', models.CharField(blank=True, max_length=120)),
                ('provincia', models.CharField(default='Santa Fe', max_length=120)),
                ('pais', models.CharField(default='Argentina', max_length=120)),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicilios', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'domicilio de tercero',
                'verbose_name_plural': 'domicilios de terceros',
                'db_table': 'terceros_domiciliotercero',
                'ordering': ['tercero__denominacion', '-activo', 'tipo', '-principal', 'pk'],
                'indexes': [models.Index(fields=['tercero', 'activo', 'tipo'], name='idx_dom_tercero_act_tipo')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True), ('principal', True)), fields=('tercero', 'tipo'), name='uniq_dom_tercero_tipo_principal'), models.CheckConstraint(condition=models.Q(('principal', False), ('activo', True), _connector='OR'), name='chk_dom_principal_activo'), models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_dom_tercero_fechas'), models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_dom_tercero_activo_sin_baja')],
            },
        ),
        migrations.CreateModel(
            name='ContactoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=180)),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'contacto de tercero',
                'verbose_name_plural': 'contactos de terceros',
                'db_table': 'terceros_contactotercero',
                'ordering': ['tercero__denominacion', '-activo', '-principal', 'nombre', 'pk'],
                'indexes': [models.Index(fields=['tercero', 'activo', 'principal'], name='idx_contacto_tercero_act')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True), ('principal', True)), fields=('tercero',), name='uniq_contacto_tercero_principal'), models.CheckConstraint(condition=models.Q(('principal', False), ('activo', True), _connector='OR'), name='chk_contacto_principal_activo'), models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_contacto_tercero_fechas'), models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_contacto_activo_sin_baja')],
            },
        ),
        migrations.CreateModel(
            name='TerceroRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=20)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'rol de tercero',
                'verbose_name_plural': 'roles de terceros',
                'db_table': 'terceros_tercerorol',
                'ordering': ['tercero__empresa__razon_social', 'tercero__denominacion', '-activo', 'rol'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tercero', 'rol'), name='uniq_tercero_rol_activo'), models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_tercero_rol_fechas'), models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_tercero_rol_activo_sin_baja')],
            },
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['empresa', 'activo', 'denominacion'], name='idx_tercero_emp_act_den'),
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['empresa', 'tipo_documento', 'numero_documento'], name='idx_tercero_emp_doc'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_tercero_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento', ''), _negated=True), fields=('empresa', 'tipo_documento', 'numero_documento'), name='uniq_tercero_empresa_documento'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_tercero_fechas'),
        ),
        migrations.AddConstraint(
            model_name='tercero',
            constraint=models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_tercero_activo_sin_baja'),
        ),
    ]
