# Generated by Django 5.2.15 on 2026-06-18 03:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIT debe contener 11 dígitos sin guiones.', regex='^\\d{11}$')])),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200)),
                ('condicion_iva', models.CharField(choices=[('RESPONSABLE_INSCRIPTO', 'Responsable inscripto'), ('MONOTRIBUTO', 'Monotributo'), ('EXENTO', 'Exento'), ('CONSUMIDOR_FINAL', 'Consumidor final'), ('NO_CATEGORIZADO', 'No categorizado')], default='RESPONSABLE_INSCRIPTO', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('provincia', models.CharField(default='Santa Fe', max_length=120)),
                ('pais', models.CharField(default='Argentina', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['empresa__razon_social', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_sucursal_empresa_codigo')],
            },
        ),
    ]
