# Generated by Django 5.2.15 on 2026-06-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('BLOQUEADO', 'Bloqueado')], default='ABIERTO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios_fiscales', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'ejercicio fiscal',
                'verbose_name_plural': 'ejercicios fiscales',
                'ordering': ['empresa__razon_social', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('BLOQUEADO', 'Bloqueado')], default='ABIERTO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='nucleo.ejerciciofiscal')),
            ],
            options={
                'verbose_name': 'periodo contable',
                'verbose_name_plural': 'periodos contables',
                'ordering': ['ejercicio__empresa__razon_social', 'ejercicio__fecha_inicio', 'fecha_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='ejerciciofiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_ejercicio_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='ejerciciofiscal',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__gte', models.F('fecha_inicio'))), name='chk_ejercicio_fecha_cierre_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='periodocontable',
            constraint=models.UniqueConstraint(fields=('ejercicio', 'codigo'), name='uniq_periodo_ejercicio_codigo'),
        ),
        migrations.AddConstraint(
            model_name='periodocontable',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__gte', models.F('fecha_inicio'))), name='chk_periodo_fecha_cierre_gte_inicio'),
        ),
    ]
