# Generated by Django 5.2.15 on 2026-06-18 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_ejerciciofiscal_periodocontable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='nucleo.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario por empresa',
                'verbose_name_plural': 'usuarios por empresa',
                'ordering': ['usuario__username', 'empresa__razon_social'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='uniq_usuario_empresa')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='nucleo.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario por sucursal',
                'verbose_name_plural': 'usuarios por sucursal',
                'ordering': ['usuario__username', 'sucursal__empresa__razon_social', 'sucursal__codigo'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'sucursal'), name='uniq_usuario_sucursal')],
            },
        ),
    ]
