# Generated by Django 5.2.15 on 2026-06-18 03:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_usuarioempresa_usuariosucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('GLOBAL', 'Global'), ('EMPRESA', 'Empresa')], default='EMPRESA', max_length=20)),
                ('clave', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator(message='La clave debe usar minúsculas, números, punto, guion o guion bajo.', regex='^[a-z0-9_.-]+$')])),
                ('valor', models.TextField(blank=True)),
                ('tipo_valor', models.CharField(choices=[('TEXTO', 'Texto'), ('ENTERO', 'Entero'), ('DECIMAL', 'Decimal'), ('BOOLEANO', 'Booleano'), ('JSON', 'JSON')], default='TEXTO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_sistema', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'parámetro del sistema',
                'verbose_name_plural': 'parámetros del sistema',
                'ordering': ['ambito', 'empresa__razon_social', 'clave'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('clave',), name='uniq_parametro_global_clave'), models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'clave'), name='uniq_parametro_empresa_clave'), models.CheckConstraint(condition=models.Q(models.Q(('ambito', 'GLOBAL'), ('empresa__isnull', True)), models.Q(('ambito', 'EMPRESA'), ('empresa__isnull', False)), _connector='OR'), name='chk_parametro_ambito_empresa')],
            },
        ),
    ]
