# Generated by Django 5.2.15 on 2026-06-18 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_parametrosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('INSERT', 'Insertar'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ANULAR', 'Anular'), ('CONFIRMAR', 'Confirmar'), ('CERRAR_PERIODO', 'Cerrar periodo'), ('ABRIR_PERIODO', 'Abrir periodo')], db_index=True, max_length=30)),
                ('tabla', models.CharField(db_index=True, max_length=120)),
                ('registro_id', models.CharField(blank=True, max_length=80)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='nucleo.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoría',
                'verbose_name_plural': 'auditoría',
                'db_table': 'nucleo_auditoria',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['empresa', '-creado_en'], name='idx_auditoria_empresa_fecha'), models.Index(fields=['accion', '-creado_en'], name='idx_auditoria_accion_fecha'), models.Index(fields=['tabla', 'registro_id'], name='idx_auditoria_tabla_registro')],
            },
        ),
    ]
