# Generated by Django 5.2.15 on 2026-06-18 13:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=80, validators=[django.core.validators.RegexValidator(message='El tipo de evento debe usar mayúsculas, números y guion bajo.', regex='^[A-Z0-9_]+$')])),
                ('entidad_tipo', models.CharField(db_index=True, max_length=120)),
                ('entidad_id', models.CharField(blank=True, max_length=80)),
                ('fecha_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error'), ('IGNORADO', 'Ignorado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_negocio', to='nucleo.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de negocio',
                'verbose_name_plural': 'eventos de negocio',
                'db_table': 'nucleo_eventonegocio',
                'ordering': ['-fecha_evento', '-creado_en'],
                'indexes': [models.Index(fields=['empresa', '-fecha_evento'], name='idx_evento_empresa_fecha'), models.Index(fields=['tipo_evento', '-fecha_evento'], name='idx_evento_tipo_fecha'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='idx_evento_entidad')],
            },
        ),
    ]
