# Generated by Django 5.2.15 on 2026-06-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_eventonegocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(db_index=True, max_length=120)),
                ('entidad_id', models.CharField(db_index=True, max_length=80)),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=120)),
                ('ruta', models.CharField(help_text='Ruta relativa dentro del almacenamiento local media/.', max_length=500)),
                ('tamanio_bytes', models.PositiveBigIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_adjuntos', to='nucleo.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_adjuntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento adjunto',
                'verbose_name_plural': 'documentos adjuntos',
                'db_table': 'nucleo_documentoadjunto',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['empresa', '-creado_en'], name='idx_documento_empresa_fecha'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='idx_documento_entidad'), models.Index(fields=['activo', '-creado_en'], name='idx_documento_activo_fecha')],
            },
        ),
    ]
