# Generated by Django 5.2.15 on 2026-06-18 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_documentoadjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='El código del permiso debe usar el formato modulo.accion en minúsculas.', regex='^[a-z0-9_]+\\.[a-z0-9_]+$')])),
                ('modulo', models.CharField(blank=True, db_index=True, max_length=60, validators=[django.core.validators.RegexValidator(message='El módulo debe usar minúsculas, números y guion bajo.', regex='^[a-z0-9_]+$')])),
                ('accion', models.CharField(blank=True, db_index=True, max_length=60, validators=[django.core.validators.RegexValidator(message='La acción debe usar minúsculas, números y guion bajo.', regex='^[a-z0-9_]+$')])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'permiso funcional',
                'verbose_name_plural': 'permisos funcionales',
                'db_table': 'nucleo_permisofuncional',
                'ordering': ['modulo', 'accion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RolFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código del rol debe usar mayúsculas, números y guion bajo.', regex='^[A-Z0-9_]+$')])),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rol funcional',
                'verbose_name_plural': 'roles funcionales',
                'db_table': 'nucleo_rolfuncional',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_asignados', to='nucleo.permisofuncional')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_asignados', to='nucleo.rolfuncional')),
            ],
            options={
                'verbose_name': 'permiso por rol',
                'verbose_name_plural': 'permisos por rol',
                'db_table': 'nucleo_rolpermiso',
                'ordering': ['rol__codigo', 'permiso__codigo'],
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='uniq_rol_permiso')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRolEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_roles', to='nucleo.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_empresa', to='nucleo.rolfuncional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rol de usuario por empresa',
                'verbose_name_plural': 'roles de usuario por empresa',
                'db_table': 'nucleo_usuariorolempresa',
                'ordering': ['usuario__username', 'empresa__razon_social', 'rol__codigo'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa', 'rol'), name='uniq_usuario_rol_empresa')],
            },
        ),
    ]
