# Generated by Django 5.2.15 on 2026-06-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_roles_permisos_funcionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFiscalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturaleza', models.CharField(blank=True, choices=[('PERSONA_HUMANA', 'Persona humana'), ('PERSONA_JURIDICA', 'Persona jurídica'), ('SUCESION_INDIVISA', 'Sucesión indivisa'), ('OTRA', 'Otra')], default='', max_length=30)),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True)),
                ('mes_cierre_ejercicio_predeterminado', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('apellido_materno', models.CharField(blank=True, max_length=120)),
                ('nombres', models.CharField(blank=True, max_length=160)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_fiscal', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'perfil fiscal de empresa',
                'verbose_name_plural': 'perfiles fiscales de empresa',
                'db_table': 'nucleo_perfilfiscalempresa',
                'ordering': ['empresa__razon_social'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mes_cierre_ejercicio_predeterminado__isnull', True), models.Q(('mes_cierre_ejercicio_predeterminado__gte', 1), ('mes_cierre_ejercicio_predeterminado__lte', 12)), _connector='OR'), name='chk_perfil_fiscal_mes_cierre')],
            },
        ),
    ]
