# Generated by Django 5.2.15 on 2026-06-20 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_perfil_fiscal_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='barrio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='departamento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_casa_central',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_deposito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_domicilio_fiscal_nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_domicilio_fiscal_provincial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_domicilio_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_local_comercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_oficina_administrativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='es_principal_actividades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='otras_funciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='partido_departamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='piso',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sector',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='torre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El código debe usar mayúsculas, números, guion o guion bajo.', regex='^[A-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='domicilio',
            field=models.CharField(blank=True, help_text='Dirección anterior conservada durante la transición al domicilio estructurado.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_casa_central', True)), fields=('empresa',), name='uniq_suc_emp_casa_central'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_domicilio_fiscal_nacional', True)), fields=('empresa',), name='uniq_suc_emp_fiscal_nac'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_domicilio_fiscal_provincial', True)), fields=('empresa',), name='uniq_suc_emp_fiscal_prov'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_domicilio_legal', True)), fields=('empresa',), name='uniq_suc_emp_legal'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_principal_actividades', True)), fields=('empresa',), name='uniq_suc_emp_principal_act'),
        ),
    ]
