# Generated by Django 5.2.15 on 2026-06-20 22:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_sucursal_domicilio_funciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCatalogoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclador', models.CharField(choices=[('ARCA_CLAE', 'ARCA - CLAE F. 883')], default='ARCA_CLAE', max_length=30)),
                ('fuente_url', models.URLField(max_length=500)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('total_registros', models.PositiveIntegerField()),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('reactivados', models.PositiveIntegerField(default=0)),
                ('desactivados', models.PositiveIntegerField(default=0)),
                ('importada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'importacion de catalogo de actividades',
                'verbose_name_plural': 'importaciones de catalogos de actividades',
                'db_table': 'nucleo_importacioncatalogoactividad',
                'ordering': ['-importada_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclador', models.CharField(choices=[('ARCA_CLAE', 'ARCA - CLAE F. 883')], default='ARCA_CLAE', max_length=30)),
                ('codigo', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='El codigo de actividad debe contener exactamente 6 digitos.', regex='^\\d{6}$')])),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fuente_url', models.URLField(blank=True, max_length=500)),
                ('fuente_sha256', models.CharField(blank=True, max_length=64)),
                ('primera_importacion_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_sincronizacion_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'actividad economica',
                'verbose_name_plural': 'actividades economicas',
                'db_table': 'nucleo_actividadeconomica',
                'ordering': ['nomenclador', 'codigo'],
                'indexes': [models.Index(fields=['nomenclador', 'activa', 'codigo'], name='idx_actividad_nom_act_cod')],
                'constraints': [models.UniqueConstraint(fields=('nomenclador', 'codigo'), name='uniq_actividad_nomenclador_codigo')],
            },
        ),
    ]
