# Generated by Django 5.2.15 on 2026-06-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_catalogo_actividades_arca'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('nomenclador_registrado', models.CharField(blank=True, default='', editable=False, max_length=30)),
                ('codigo_registrado', models.CharField(blank=True, default='', editable=False, max_length=6)),
                ('descripcion_registrada', models.TextField(blank=True, default='', editable=False)),
                ('fuente_sha256_registrada', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_empresa', to='nucleo.actividadeconomica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_economicas', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'actividad económica de empresa',
                'verbose_name_plural': 'actividades económicas de empresa',
                'db_table': 'nucleo_empresaactividad',
                'ordering': ['empresa__razon_social', '-activa', '-principal', 'orden', 'codigo_registrado'],
                'indexes': [models.Index(fields=['empresa', 'activa', 'principal', 'orden'], name='idx_emp_act_estado')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('empresa', 'actividad'), name='uniq_emp_actividad_activa'), models.UniqueConstraint(condition=models.Q(('activa', True), ('principal', True)), fields=('empresa',), name='uniq_emp_actividad_principal'), models.CheckConstraint(condition=models.Q(('principal', False), ('activa', True), _connector='OR'), name='chk_emp_act_principal_activa'), models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), models.Q(('vigencia_desde__isnull', False), ('vigencia_hasta__gte', models.F('vigencia_desde'))), _connector='OR'), name='chk_emp_act_vigencia')],
            },
        ),
    ]
