# Generated by Django 5.2.15 on 2026-06-21 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_empresa_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIIBBEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen', models.CharField(choices=[('NO_INSCRIPTO', 'No inscripto'), ('LOCAL', 'Contribuyente local'), ('CONVENIO_MULTILATERAL', 'Convenio Multilateral')], max_length=30)),
                ('tratamiento_general', models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('NO_ALCANZADO', 'No alcanzado'), ('MIXTO', 'Mixto')], default='GRAVADO', max_length=20)),
                ('numero_inscripcion', models.CharField(blank=True, max_length=50)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_iibb', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'configuración de Ingresos Brutos',
                'verbose_name_plural': 'configuraciones de Ingresos Brutos',
                'db_table': 'nucleo_configuracionesiibbempresa',
                'ordering': ['empresa__razon_social', '-activa', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='JurisdiccionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='El código COMARB debe contener tres dígitos.', regex='^9\\d{2}$')])),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fuente_url', models.URLField(blank=True, max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'jurisdicción fiscal',
                'verbose_name_plural': 'jurisdicciones fiscales',
                'db_table': 'nucleo_jurisdiccionfiscal',
                'ordering': ['orden', 'codigo'],
                'indexes': [models.Index(fields=['activa', 'orden', 'codigo'], name='idx_jur_fiscal_act_ord')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaJurisdiccionIIBB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscripcion', models.CharField(blank=True, max_length=50)),
                ('sede', models.BooleanField(default=False)),
                ('tratamiento', models.CharField(choices=[('SEGUN_CONFIGURACION', 'Según configuración general'), ('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('NO_ALCANZADO', 'No alcanzado'), ('MIXTO', 'Mixto')], default='SEGUN_CONFIGURACION', max_length=25)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('codigo_registrado', models.CharField(blank=True, default='', editable=False, max_length=3)),
                ('nombre_registrado', models.CharField(blank=True, default='', editable=False, max_length=120)),
                ('fuente_url_registrada', models.URLField(blank=True, default='', editable=False, max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdicciones', to='nucleo.configuracioniibbempresa')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_empresa', to='nucleo.jurisdiccionfiscal')),
            ],
            options={
                'verbose_name': 'jurisdicción de Ingresos Brutos',
                'verbose_name_plural': 'jurisdicciones de Ingresos Brutos',
                'db_table': 'nucleo_empresajurisdicioniibb',
                'ordering': ['configuracion__empresa__razon_social', '-activa', '-sede', 'jurisdiccion__orden'],
            },
        ),
        migrations.AddIndex(
            model_name='configuracioniibbempresa',
            index=models.Index(fields=['empresa', 'activa', 'regimen'], name='idx_config_iibb_emp_est'),
        ),
        migrations.AddConstraint(
            model_name='configuracioniibbempresa',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('empresa',), name='uniq_emp_config_iibb_activa'),
        ),
        migrations.AddConstraint(
            model_name='configuracioniibbempresa',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), models.Q(('fecha_alta__isnull', False), ('fecha_baja__gte', models.F('fecha_alta'))), _connector='OR'), name='chk_config_iibb_fechas'),
        ),
        migrations.AddConstraint(
            model_name='configuracioniibbempresa',
            constraint=models.CheckConstraint(condition=models.Q(('activa', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_config_iibb_activa_sin_baja'),
        ),
        migrations.AddIndex(
            model_name='empresajurisdiccioniibb',
            index=models.Index(fields=['configuracion', 'activa', 'sede'], name='idx_jur_iibb_config_est'),
        ),
        migrations.AddConstraint(
            model_name='empresajurisdiccioniibb',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('configuracion', 'jurisdiccion'), name='uniq_config_jur_iibb_activa'),
        ),
        migrations.AddConstraint(
            model_name='empresajurisdiccioniibb',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('sede', True)), fields=('configuracion',), name='uniq_config_jur_iibb_sede'),
        ),
        migrations.AddConstraint(
            model_name='empresajurisdiccioniibb',
            constraint=models.CheckConstraint(condition=models.Q(('sede', False), ('activa', True), _connector='OR'), name='chk_jur_iibb_sede_activa'),
        ),
        migrations.AddConstraint(
            model_name='empresajurisdiccioniibb',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), models.Q(('fecha_alta__isnull', False), ('fecha_baja__gte', models.F('fecha_alta'))), _connector='OR'), name='chk_jur_iibb_fechas'),
        ),
        migrations.AddConstraint(
            model_name='empresajurisdiccioniibb',
            constraint=models.CheckConstraint(condition=models.Q(('activa', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_jur_iibb_activa_sin_baja'),
        ),
    ]
