# Generated by Django 5.2.15 on 2026-06-21 02:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_cargar_jurisdicciones_fiscales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99998)])),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200)),
                ('sistema_emision', models.CharField(choices=[('WEB_SERVICE', 'Factura electrónica - Web Services'), ('COMPROBANTES_EN_LINEA', 'Comprobantes en línea'), ('CONTROLADOR_FISCAL', 'Controlador fiscal'), ('FACTURADOR', 'Facturador'), ('MANUAL', 'Comprobantes manuales'), ('OTRO', 'Otro sistema')], max_length=30)),
                ('descripcion_sistema_arca', models.CharField(blank=True, help_text='Descripción exacta observada en ARCA, cuando sea necesario conservarla.', max_length=200)),
                ('predeterminado', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actividad_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta_predeterminados', to='nucleo.empresaactividad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='nucleo.empresa')),
                ('jurisdiccion_iibb_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta_predeterminados', to='nucleo.empresajurisdiccioniibb')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'db_table': 'nucleo_puntoventa',
                'ordering': ['empresa__razon_social', '-activo', 'sucursal__codigo', 'numero'],
                'indexes': [models.Index(fields=['empresa', 'activo', 'numero'], name='idx_pv_emp_act_num'), models.Index(fields=['sucursal', 'activo', 'predeterminado'], name='idx_pv_suc_act_def')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_pv_empresa_numero'), models.UniqueConstraint(condition=models.Q(('activo', True), ('predeterminado', True)), fields=('sucursal',), name='uniq_pv_suc_default_activo'), models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 99998)), name='chk_pv_numero_rango'), models.CheckConstraint(condition=models.Q(('fecha_baja__isnull', True), ('fecha_alta__isnull', True), ('fecha_baja__gte', models.F('fecha_alta')), _connector='OR'), name='chk_pv_fechas'), models.CheckConstraint(condition=models.Q(('activo', False), ('fecha_baja__isnull', True), _connector='OR'), name='chk_pv_activo_sin_baja'), models.CheckConstraint(condition=models.Q(('predeterminado', False), ('activo', True), _connector='OR'), name='chk_pv_default_activo')],
            },
        ),
    ]
