# Generated by Django 5.2.15 on 2026-06-30 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_item_proveedor'),
        ('nucleo', '0015_puntos_venta'),
        ('terceros', '0003_grupos_terceros'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_arca', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('abreviatura', models.CharField(max_length=20)),
                ('clase', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('M', 'M'), ('X', 'Interno')], max_length=1)),
                ('especie', models.CharField(choices=[('FACTURA', 'Factura'), ('NOTA_DEBITO', 'Nota de debito'), ('NOTA_CREDITO', 'Nota de credito'), ('RECIBO', 'Recibo'), ('REMITO', 'Remito'), ('OTRO', 'Otro')], max_length=20)),
                ('signo', models.SmallIntegerField(choices=[(1, 'Positivo'), (-1, 'Negativo'), (0, 'Neutro')], default=1)),
                ('mueve_iva', models.BooleanField(default=True)),
                ('requiere_comprobante_asociado', models.BooleanField(default=False)),
                ('electronico', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de comprobante de venta',
                'verbose_name_plural': 'tipos de comprobante de venta',
                'db_table': 'ventas_tipocomprobanteventa',
                'ordering': ['codigo_arca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cliente_denominacion', models.CharField(max_length=200)),
                ('cliente_tipo_documento_codigo', models.CharField(blank=True, max_length=30)),
                ('cliente_numero_documento', models.CharField(blank=True, max_length=30)),
                ('cliente_condicion_iva_codigo', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('subtotal_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_tributos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_venta', to='terceros.tercero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_venta', to='nucleo.empresa')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_venta', to='nucleo.puntoventa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_venta', to='nucleo.sucursal')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_venta', to='ventas.tipocomprobanteventa')),
            ],
            options={
                'verbose_name': 'comprobante de venta',
                'verbose_name_plural': 'comprobantes de venta',
                'db_table': 'ventas_comprobanteventa',
                'ordering': ['empresa__razon_social', '-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='ventas.comprobanteventa')),
            ],
            options={
                'verbose_name': 'tributo de comprobante de venta',
                'verbose_name_plural': 'tributos de comprobante de venta',
                'db_table': 'ventas_comprobanteventatributo',
                'ordering': ['comprobante_id', 'codigo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AJUSTE', 'Ajuste'), ('REFERENCIA', 'Referencia')], default='AJUSTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones', to='ventas.comprobanteventa')),
                ('comprobante_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_que_lo_asocian', to='ventas.comprobanteventa')),
            ],
            options={
                'verbose_name': 'comprobante de venta asociado',
                'verbose_name_plural': 'comprobantes de venta asociados',
                'db_table': 'ventas_comprobanteventaasociado',
                'ordering': ['comprobante_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('comprobante', 'comprobante_asociado'), name='uniq_cva_comprobante_asociado'), models.CheckConstraint(condition=models.Q(('comprobante', models.F('comprobante_asociado')), _negated=True), name='chk_cva_no_autoasociado')],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('importe_iva', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('alicuota_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='totales_iva_venta', to='items.alicuotaiva')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_iva', to='ventas.comprobanteventa')),
            ],
            options={
                'verbose_name': 'IVA de comprobante de venta',
                'verbose_name_plural': 'IVA de comprobantes de venta',
                'db_table': 'ventas_comprobanteventaiva',
                'ordering': ['comprobante_id', 'alicuota_iva__porcentaje'],
                'constraints': [models.UniqueConstraint(fields=('comprobante', 'alicuota_iva'), name='uniq_cvi_comprobante_alicuota')],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tratamiento_iva', models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('NO_GRAVADO', 'No gravado')], default='GRAVADO', max_length=20)),
                ('subtotal_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('iva_importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('alicuota_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='items.alicuotaiva')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.comprobanteventa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='items.item')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='items.unidadmedida')),
            ],
            options={
                'verbose_name': 'linea de comprobante de venta',
                'verbose_name_plural': 'lineas de comprobante de venta',
                'db_table': 'ventas_comprobanteventalinea',
                'ordering': ['comprobante_id', 'numero_linea'],
                'constraints': [models.UniqueConstraint(fields=('comprobante', 'numero_linea'), name='uniq_cvl_comprobante_linea'), models.CheckConstraint(condition=models.Q(('descuento_porcentaje__gte', 0), ('descuento_porcentaje__lte', 100)), name='chk_cvl_descuento_rango'), models.CheckConstraint(condition=models.Q(models.Q(('alicuota_iva__isnull', False), ('tratamiento_iva', 'GRAVADO')), models.Q(models.Q(('tratamiento_iva', 'GRAVADO'), _negated=True), ('alicuota_iva__isnull', True)), _connector='OR'), name='chk_cvl_tratamiento_iva')],
            },
        ),
        migrations.AddIndex(
            model_name='comprobanteventa',
            index=models.Index(fields=['empresa', 'fecha'], name='idx_cv_emp_fecha'),
        ),
        migrations.AddIndex(
            model_name='comprobanteventa',
            index=models.Index(fields=['empresa', 'estado', 'fecha'], name='idx_cv_emp_est_fecha'),
        ),
        migrations.AddIndex(
            model_name='comprobanteventa',
            index=models.Index(fields=['empresa', 'cliente'], name='idx_cv_emp_cliente'),
        ),
        migrations.AddConstraint(
            model_name='comprobanteventa',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('empresa', 'tipo_comprobante', 'punto_venta', 'numero'), name='uniq_cv_emp_tipo_pv_num'),
        ),
        migrations.AddConstraint(
            model_name='comprobanteventa',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha')), _connector='OR'), name='chk_cv_fechas'),
        ),
        migrations.AddConstraint(
            model_name='comprobanteventa',
            constraint=models.CheckConstraint(condition=models.Q(('numero__isnull', True), ('punto_venta__isnull', False), _connector='OR'), name='chk_cv_numero_requiere_pv'),
        ),
    ]
